name: DocC

on:
  workflow_dispatch:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

jobs:
  docs:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Checkout Docs Repo
      uses: actions/checkout@v2
      with:
        repository: heestand-xyz/AsyncGraphics-Docs
        ref: main
        path: AsyncGraphics-Docs
    - name: Pre Cat Test
      run: cat AsyncGraphics-Docs/test.txt
    - name: Echo Test
      run: echo 1 >> AsyncGraphics-Docs/test.txt
    - name: Post Cat Test
      run: cat AsyncGraphics-Docs/test.txt
      
