name: DocC

on:
  workflow_dispatch:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  #push:
  #  tags:
  #    - "*"

jobs:
  docs:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Checkout Docs Repo
      uses: actions/checkout@v3
      with:
        repository: heestand-xyz/AsyncGraphics-Docs
        ref: main
        path: ../AsyncGraphics-Docs
        
    - name: Test 1 2 3
      run: |
        cd ../AsyncGraphics-Docs        
        cat test.txt
        echo 123 >> test.txt
        cat test.txt

    - name: Configure Git
      run: |
        cd ../AsyncGraphics-Docs        
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Commit to Docs Repo
      run: |
        cd ../AsyncGraphics-Docs        
        echo here...
        pwd
        git add .
        git commit -m "Test 1 2 3"

    - name: Push to Docs Repo
      run: |
        cd ../AsyncGraphics-Docs        
        git push origin main
